
services:
  'mrapps.amazon.s3':
      class: 'Mrapps\AmazonBundle\Handler\S3Handler'
      arguments:
        - 'Doctrine\ORM\EntityManagerInterface'
        - '@liip_imagine.controller'
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''