
services:
  'mrapps.amazon.s3':
      class: 'Mrapps\AmazonBundle\Handler\S3Handler'
      arguments:
        - 'Doctrine\ORM\EntityManagerInterface'
        - '@liip_imagine.controller'
        - '%mrapps_amazon.parameters.access%'
        - '%mrapps_amazon.parameters.secret%'
        - '%mrapps_amazon.parameters.region%'
        - '%mrapps_amazon.parameters.default_bucket%'
        - '%mrapps_amazon.cdn.enable%'
        - '%mrapps_amazon.cdn.url%'