<?php

namespace Mrapps\AmazonBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Mrapps\AmazonBundle\Entity\S3Object;

/**
 * S3ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S3ObjectRepository extends EntityRepository
{
    public function setEtag($key = '', $etag = '', $updatedAt = null) {
        
        $key = trim($key);
        $etag = trim($etag);
        
        if(strlen($key) > 0 && strlen($etag) > 0) {
            
            $em = $this->getEntityManager();
            $object = $this->findOneBy(array('s3Key' => $key));
            
            if(is_null($object)) {
                
                $object = new S3Object();
                $object->setS3Key($key);
            }
            
            if($object->getEtag() !== $etag) $object->setUpdatedAt($updatedAt);
            $object->setEtag($etag);
            
            $em->persist($object);
            $em->flush($object);
            
            return $object;
        }
        
        return null;
    }
    
    public function getEtag($key = '') {
        
        $key = trim($key);
        if(strlen($key) > 0) {
            $object = $this->findOneBy(array('s3Key' => $key));
            return ($object !== null) ? $object->getEtag() : '';
        }
        
        return '';
    }
    
    public function getUpdatedAt($key = '') {
        
        $key = trim($key);
        if(strlen($key) > 0) {
            $object = $this->findOneBy(array('s3Key' => $key));
            return ($object !== null) ? $object->getUpdatedAt() : null;
        }
        
        return '';
    }
}
